name: pypi
on:
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - uses: astral-sh/setup-uv@v7
      - name: Build dists
        run: make build
      - name: Pypi Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
